[package]
name = "car-vision"
version = "0.1.0"
edition = "2024"
default-run = "car-vision"

[dependencies]
bevy = { workspace = true }
crossbeam = { workspace = true }
bevy_egui = { workspace = true }
bevy_pointcloud = { workspace = true }
